owner: 1mfaasj
repo: uppie

sites:
  - name: Plaus
    url: $PLAUS
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: Graf
    url: $GRAF
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
# dit is 10 sec

assignees:
  - 1mfaasj

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  cname: uppie.d4bbe.com
  name: Uppie
  introTitle: "**Uppie** de status pagina"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
