owner: 1mfaasj
repo: uppie

sites:
  - name: Hier
    url: $HIER
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
  - name: Daar
    url: $DAAR
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
# dit is 10 sec

assignees:
  - 1mfaasj

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  cname: uppie.d4bbe.com
  name: Uppie
  introTitle: "**Uppie** de status pagina"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  activeIncidents: Actieve incidenten
  allSystemsOperational: Alles is operationeel
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Geopend op $DATE met $POSTS posts
  incidentTitle: Incident $NUMBER details
  incidentDetails: Incident details
  incidentFixed: Opgelost
  incidentOngoing: Ongoing
  incidentOpenedAt: Geopend op
  incidentClosedAt: Gesloten op
  incidentViewOnGitHub: Bekijk en abonneer op GitHub
  incidentCommentSummary: Geplaatst op $DATE door $AUTHOR
  incidentBack: ← Terug naar alle incidenten
  pastIncidents: Incidenten uit het verleden
  pastIncidentsResolved: Opgelost in $MINUTES minuten met $POSTS berichten
  liveStatus: Live status
  overallUptime: "Overal uptime: $UPTIME"
  overallUptimeTitle: Overal uptime
  averageResponseTime: "Gemiddelde reactietijd: $TIMEms"
  averageResponseTimeTitle: Gemiddelde reactie
  sevelDayResponseTime: 7-dagen reactietijd
  responseTimeMs: Reactietijd (ms)
  up: Online
  down: Offline
  degraded: Gedegradeerd
  loading: Laden
  footer: .
  errorTitle: Er is een fout opgetreden
  errorIntro: Er is een fout opgetreden bij het ophalen van de meest recente statusgegevens.
  errorText: Je kunt het over enkele ogenblikken opnieuw proberen.
  errorHome: Ga naar de voorpagina
  pastScheduledMaintenance: Eerder gepland onderhoud
  scheduledMaintenance: Gepland onderhoud
  scheduledMaintenanceSummaryStarted: Gestart op $DATE voor $DURATION minuten
  scheduledMaintenanceSummaryStarts: Begint op $DATE voor $DURATION minuten
  startedAt: Begonnen op
  startsAt: Begint om
  duration: Duur
  durationMin: $DURATION minuten
  incidentCompleted: Voltooid
  incidentScheduled: Gepland
  duration24H: 24uur
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1jaar
  durationAll: alles
